name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publishing ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [windows]
        include:
          - build_target: windows
            os: windows-latest
            artifact_prefix: macos
            target: x86_64-pc-windows-msvc
            features: '--no-default-features --features rodio_backend,cursive/pancurses-backend'
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
          profile: minimal
      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install portaudio pkg-config
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libpulse-dev libdbus-1-dev libncursesw5-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions/checkout@v2
        name: Checkout src
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Running cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release --target ${{ matrix.target }} ${{ matrix.features }}
      - name: Extract git tag
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
      - name: Packaging assets (Linux and Mac OS)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          strip ncspot
          tar czvf ncspot-${{ steps.extract_tag.outputs.tag }}-${{ matrix.artifact_prefix }}.tar.gz ncspot
          shasum -a 256 ncspot-${{ steps.extract_tag.outputs.tag }}-${{ matrix.artifact_prefix }}.tar.gz > ncspot-${{ steps.extract_tag.outputs.tag }}-${{ matrix.artifact_prefix }}.sha256
      - name: Packaging assets (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          strip ncspot.exe
          mv ncspot.exe ncspot-${{ steps.extract_tag.outputs.tag }}-${{ matrix.artifact_prefix }}.exe
          certutil -hashfile ncspot-${{ steps.extract_tag.outputs.tag }}-${{ matrix.artifact_prefix }}.exe sha256 > ncspot-${{ steps.extract_tag.outputs.tag }}-${{ matrix.artifact_prefix }}.sha256
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/ncspot-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
